---
# tasks file for docker_prod
- name: Ensure docker packages is present
  apt: name=docker.io state=present

- name: Ensure python-pip packages is present
  apt: name=python-pip state=present

- name: Ensure python-py packages is present
  pip: 
    name: docker-py

- name: Container present
  docker_container:
    name: prod
    image: tomcat:jre8-alpine
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /home/master/ansible-docker/docker_prod/files/hello-1.0.war:/var/lib/tomcat9/webapps/
