---
# tasks file for docker_prod
- name: Ensure docker packages is present
  apt: name=docker.io state=present

- name: Ensure python-pip packages is present
  apt: name=python-pip state=present

- name: Ensure python-pip packages is present
  pip: 
    install: 
    - docker

- name: Container present
  docker_container:
    name: prod
    image: tomcat:jre8-alpine
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /var/lib/tomcat9/webapps/
