---
# tasks file for docker_prod
- name: Ensure docker packages is present
  apt: name=docker.io state=present

- name: Container present
  community.docker.docker_container:
    name: prod
    state: present
    image: tomcat:jre8-alpine
#  copy:
#    src: /home/master/ansible-roles/artefact_builder/files/
#    dest: "{{dest_folder}}"
  ports:
   - "8080:8080"
#    volumes:
#      - hello-1.0.war:{{dest_folder}}
