---
# tasks file for docker_prod
- name: Ensure docker packages is present
  apt: name=docker.io state=present
#apt install python-pip

- name: Container present
  docker_container:
    name: prod
    image: tomcat:jre8-alpine
#    copy:
#      src: '/home/master/ansible-roles/artefact_builder/files/'
#      dest: '/var/lib/tomcat9/webapps/'
    state: started
    ports:
     - "8080:8080"
    volumes:
     - ./hello-1.0.war:/var/lib/tomcat9/webapps/
