- name: artefactory assembly configuration
  hosts: build
  become: yes
  roles:
    - common
    - artefact_builder

- name: web-server configuration
  hosts: prod
  become: yes
  roles:
    - docker_prod